version: '3.0'
services:
  flask-backend:
    image: flask-backend:1.0
    build: ./api
    ports:
      - '5555:5555'

  react-frontend:
    image: react-frontend:1.0
    build: .
    ports:
      - '3000:3000'
